name: Build ISO

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pacman -Sy --noconfirm archiso

      - name: Build ISO
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: iso
          path: out/*.iso
